name: 'AWS SQS'
description: 'Send message to AWS SQS'
branding:
  icon: 'message-square'
  color: 'orange'
inputs:
  sqs-url:
    description: 'AWS SQS url to send message'
    required: true
  message:
    description: 'message body to send'
    required: true
  message-attributes:
    description: 'message attributes to sent'
runs:
  using: 'node16'
  main: 'index.js'
